[build]
  command = "pip install -r requirements.txt"
  publish = "static"

[functions]
  included_files = ["templates/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200
